### ISSUE TITLE
Documentation tip : add artifact step

### ISSUE THREAD

**Issue by dannradkov** [denniszielke/phoenix#5]
Documentation tip : 
Could be good to describe one has to to define the artifact from the build def, when defining the release definition. Page is @  https://github.com/denniszielke/phoenix/blob/master/hints/TeamServicesToACI.md . 
Might be confusing to newbies 😄 .

Currently there are instructions to create the rel. def. but you dont say the artifact produced from the build has to be used.

**Comment by denniszielke** [comment]
True thanks for the feedback- for the ACI Release there is no need for artifacts - it just has to be there. And for the real goal - the release via Helm we have documented that step: https://github.com/denniszielke/phoenix/blob/master/hints/TeamServicesHelmK8s.md

**Comment by dannradkov** [comment]
also in https://github.com/denniszielke/phoenix/blob/master/hints/TeamServicesToACI.md the port specified is 8080 , while the Dockerfile says expose 80

**Comment by denniszielke** [comment]
Fixed!
